apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: openshift-gitops-placementbinding
  namespace: openshift-gitops
placementRef:
  name: openshift-gitops-placementrule-ocp-lab-mike
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: openshift-gitops-installed-ocp-lab-mike
    kind: Policy
    apiGroup: policy.open-cluster-management.io
  - name: project-compliance-ocp-lab-charlie
    kind: Policy
    apiGroup: policy.open-cluster-management.io
