apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: openshift-gitops-apps-subscription
  namespace: openshift-gitops
  labels:
    app: argocd-ocp-lab-mike
    app.kubernetes.io/part-of: argocd-ocp-lab-mike
    apps.open-cluster-management.io/reconcile-rate: high
  annotations:
    apps.open-cluster-management.io/deployables: ''
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-current-commit: ''
    apps.open-cluster-management.io/git-path: gitops-manifests/ocp-lab-mike
    apps.open-cluster-management.io/reconcile-option: replace
spec:
  channel: rhacm-gitops-ns-ocp-lab-mike/rhacm-gitops-ocp-lab-mike
  placement:
    placementRef:
      kind: PlacementRule
      name: openshift-gitops-placementrule-ocp-lab-mike
