- op: replace
  path: /metadata/labels
  value:
    app: argocd-ocp-lab-charlie
- op: replace
  path: /spec/selector
  value:
    matchExpressions:
      - key: app
        operator: In
        values:
          - argocd-ocp-lab-charlie
