bases:
  - ../../base/
resources:
  - policy/placementbinding-openshift-gitops.yaml
  - policy/policy-openshift-gitops.yaml
  - placementrule-openshift-gitops.yaml
  - subscription-openshift-gitops-apps.yaml
nameSuffix: "-ocp-lab-charlie"
patches:
- path: channel-openshift-gitops-ocp-lab-charlie.yaml
  target:
    group: apps.open-cluster-management.io
    version: v1
    kind: Channel
    name: rhacm-gitops
    namespace: rhacm-gitops-ns
- path: application-openshift-gitops-ocp-lab-charlie.yaml
  target:
    group: app.k8s.io
    version: v1beta1
    kind: Application
    name: argocd
    namespace: openshift-gitops
- path: namespace-channel-ocpgitops-ocp-lab-charlie.yaml
  target:
    version: v1
    kind: Namespace
    name: rhacm-gitops-ns

