apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: argocd-ocp-lab-charlie
spec:
  clusterResourceBlacklist:
    - group: ''
      kind: ClusterRole
    - group: ''
      kind: ClusterRoleBinding
    - group: ''
      kind: ResourceQuota
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  destinations:
    - name: in-cluster
      namespace: '*'
      server: '*'
  namespaceResourceBlacklist:
    - group: network.openshift.io
      kind: EgressNetworkPolicy
    - group: ''
      kind: ResourceQuota
  roles:
    - groups:
        - admin
      name: syncer
      policies:
        - 'p, proj:dev:syncer, applications, sync, dev/*, allow'
  sourceRepos:
    - '*'
